### ISSUE TITLE
Build break when updating to v2.1.0

### ISSUE THREAD

**Issue by orangecoding** [webpack-contrib/extract-text-webpack-plugin#454]
If I update from v 1.0.1 to 2.1.0, I'll get the following exception during build.

`extract-text-webpack-plugin/index.js:267
				var shouldExtract = !!(options.allChunks || chunk.isInitial());
				                                                  ^

TypeError: chunk.isInitial is not a function
    at /Users/Christian/dev/portal/node_modules/extract-text-webpack-plugin/index.js:267:55
    at /Users/Christian/dev/portal/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:3025:16
    at eachOfArrayLike (...)`

**Comment by scottdj92** [comment]
There were a lot of breaking changes from v1 to v2. I'm not sure if the function still exists.

**Comment by orangecoding** [comment]
Actually I am not using webpack 2. I was updating this plugin while sticking to webpack 1.

**Comment by scottdj92** [comment]
Can you post your webpack config, please?

**Comment by kostasmanionis** [comment]
`v2.1.0` won't work with webpack1, this breaking change has been added quite a while ago https://github.com/webpack-contrib/extract-text-webpack-plugin/commit/ba0a71dcc72dd298f602f96906e2042a08cbe039

I would recommend updating to webpack 2 or sticking with `v1.0.1`

**Comment by michael-ciniawsky** [comment]
@orangecoding See @kostasmanionis's comment
