### ISSUE TITLE
ERROR in ./~/bootstrap-loader/lib/bootstrap.loader.js?extractStyles!./~/bootstrap-loader/no-op.js

### ISSUE THREAD

**Issue by pavelekNET** [webpack-contrib/extract-text-webpack-plugin#364]
After updating to rc0 from 2.0.0-beta.5:

ERROR in ./~/bootstrap-loader/lib/bootstrap.loader.js?extractStyles!./~/bootstrap-loader/no-op.js
Module not found: Error: Can't resolve '[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]./lib\bootstrap.styles.loader.js' in 'C:\PROJECTS\UCB_IMPRESTO_FE\node_modules\bootstrap-loader'
 @ ./~/bootstrap-loader/lib/bootstrap.loader.js?extractStyles!./~/bootstrap-loader/no-op.js 1:21-594
 @ ./~/bootstrap-loader/extractStyles.js
 @ ./src/vendors.ts

**Comment by montijr2007** [comment]
I am having a similiar issue since the RC version was released. My builds are appear to be breaking on the new "getLoaderWithQuery(loader)" method. angular-cli depends on the most recent version ^2.0.0-beta.4 and since this upgrade, I can no longer build my project.

**Error:**
Module build failed : error : Cannot find module 'C:\MyProject\node_modules\css-loader\index.js?sourcemap&minimize'

How can I get around this issue for the time being?

**Comment by pitakill** [comment]
I can confirm this in one of my projects.

I'm working on OS X Sierra (10.2.2) if relevant.

And see a output similar to @pavelekNET:

If the full output of the error is needed, i'm glad to put it.

```
ERROR in ./~/bootstrap-loader/lib/bootstrap.loader.js?extractStyles!./~/bootstrap-loader/no-op.js
Module not found: Error: Can't resolve '[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]./lib/bootstrap.styles.loader.js?{"bootstrapVersion":3,"preBootstrapCustomizations":

```

Thank you for your effort and project. :)

**Comment by bebraw** [comment]
Can you try `extract` through `use` instead of `loader`? Let me know how it goes.

**Comment by gplume** [comment]
Same issue here with font-awesome-loader. It breaks with the same error since 2.0.0-rc.0.
I have to keep beta.4 to build my projects.
What is ```use``` instead of ```loader``` ?

**Comment by bebraw** [comment]
@gplume `use: ExtractTextPlugin.extract(...)`. That's the new syntax.

**Comment by gplume** [comment]
OK. Didn't know that! It works as before with ```use```...
thanks!

**Comment by bebraw** [comment]
@gplume Can you set up a small standalone project to study?

**Comment by gplume** [comment]
Interresting that rc.1 throws a different error now :
```
..../extract-text-webpack-plugin/schema/validator.js:10
                throw new Error(ajv.errorsText());
```
Here's a gist with rc.0, move it to beta.4 and it compile, then with rc.0/1 you have the errors:
[https://gist.github.com/gplume/c935111fc9634583a43936f309a424ba](url)

**Comment by bebraw** [comment]
@gplume Can you replace `loader: ExtractTextPlugin.extract` with `use: ExtractTextPlugin.extract` as instructed above? `loader` won't work anymore.

It would be ideal if you could provide something to run as it's very hard to debug otherwise.

**Comment by gplume** [comment]
How about the gist ? It runs ok if you pin to beta.4 or below. Only rc.x produce the error.
[example gist](https://gist.github.com/gplume/c935111fc9634583a43936f309a424ba)
Same errors with  ```use:```

**Comment by bebraw** [comment]
@gplume Why do you have `options: '/dist/'` at `extract`? That field isn't supported by the schema.

**Comment by gplume** [comment]
Yes sorry it was a try... usually it's not here. I've moved the whole gist locally to ```use:``` and now I have webpack issues like : 
```Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.rules[0].use should be one of these:
   non-empty string | function | object { loader?, options?, query? } | function | [non-empty string | function | object { loader?, options?, query? }]```
Are you sure we have to move ```loader:``` to ```use:` everywhere?
I guess I need some more reading for v2 but the webpack docs is sometimes... well I won't say it, it's a great great tool anyway!

**Comment by bebraw** [comment]
@gplume Can you set up an entire repository for me to clone? It's easier for me to see what's going on then. Note that you should use `loader` within the plugin definition itself. The error sounds like something else, though.

**Comment by gplume** [comment]
I thought the zipped gist could help? I've updated it to make use of ```use:``` and pinned it to beta.4.
``` npm install && npm run build ``` put you into context.
As soon as you upgrade extract-text plugin to rc.x, it fails.

**Comment by bebraw** [comment]
@gplume Ok, got it.

The issue happens because font-awesome-loader has a line like this in its pitch phase:

```javascript
  var styleLoaderCommand = 'require(' + JSON.stringify('-!' + styleLoader + '!' +
      require.resolve('./font-awesome-styles.loader.js') + '!' + configFilePath) + ');';
```

Since `extract` returns an object now, it will stringify it as `[object Object],[object Object],[object Object],[object Object]` for the loader query and that won't obviously work here since we don't support that form at the moment.

@insin Any thoughts on this? It's a little tricky as probably have to choose either the current format (array of objects) or the old one (querystring). The new format is handy for `use`, but it breaks loaders like font-awesome-loader and there's no way to support both.

**Comment by bebraw** [comment]
@gplume Here's a potential fix if you want to try it out, https://github.com/webpack-contrib/extract-text-webpack-plugin/pull/374 .

**Comment by bebraw** [comment]
We discussed about this. It's actually a `font-awesome-loader` issue to fix now as `ExtractTextPlugin` won't emit a string by design (problematic with function based configuration). So instead of hacking around with a custom `toString` we'll document how to fix the loader instead.

**Comment by wzup** [comment]
@bebraw 
No, it's not `font-awesome-loader`. I don't have `font-awesome-loader` and I have the error.
```
$ NODE_ENV='production' node_modules/.bin/webpack --config webpack.conf.js --progress -p --display-depth --colors --display-chunks

C:\Users\user\app\node_modules\extract-text-webpack-plugin\schema\validator.js:11
                throw new Error(ajv.errorsText());
                ^

Error: data['fallback'] should NOT have additional properties
    at validate (C:\Users\user\app\node_modules\extract-text-webpack-plugin\schema\validator.js:11:9)
    at Function.ExtractTextPlugin.extract (C:\Users\user\app\node_modules\extract-text-webpack-plugin\index.js:190:3)
    at Object.<anonymous> (C:\Users\user\app\webpack\production.browser.js:103:40)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
```

A list of modules I use:
```
            'jquery',
            'react',
            'react-dom',
            'react-sticky',
            'material-ui',
            'react-redux',
            'react-router',
            'redux-thunk',
            'redux-logger',
            'rc-slider',
            'react-addons-css-transition-group',
            'classnames',
```

**Comment by bebraw** [comment]
@wzup There's not enough information to tell what's wrong. I would need the plugin definition at least to tell why the validation is failing.

**Comment by wzup** [comment]
@bebraw I've updated my prev post

**Comment by bebraw** [comment]
@wzup Are you absolutely sure you are using rc3? rc2 would throw in the line your trace points to.

**Comment by wzup** [comment]
@bebraw 

Exactly it was `rc2`. Thank you very much for your quick response. Re-installation of the plugin solved the issue.

```
$ npm rm extract-text-webpack-plugin --save-dev
$ npm install --save-dev extract-text-webpack-plugin@beta
```

Am working on two apps with similar webpack configs and just couldn't understand why one compiles all right and the other doesn't. Didn't notice the version difference.

![extract text plugin error - sublime text - 2017-02-24 00 09 15](https://cloud.githubusercontent.com/assets/3880497/23267741/9aa1c536-fa26-11e6-8759-3608496c10d8.png)

**Comment by bebraw** [comment]
@wzup No worries. Cool to hear you got it. 👍
