### PR TITLE
Hot module replacement

### PR DESCRIPTION
**Pull request by jantimon**
This pull request adds hot module replacement to the extract-text-webpack-plugin.

### CODE REVIEW

**Comment by BohdanTkachenko** [comment]
Any chance that this PR can be merged?

**Comment by karlhorky** [comment]
+1 Yes, I'd like to have this too. @sokra does this look ok?

**Comment by jantimon** [comment]
Also the documentation said [that hot module replacement might be used in production](https://github.com/webpack/docs/wiki/hot-module-replacement-with-webpack) @sokra said that he won't merge this feature as hmr works seamless without the extract-text-webpack plugin

**Comment by readme42** [comment]
Would love to use ExtractTextPlugin with HMR!

Scenario: multiple css-themes which are extracted to static css files.

**Comment by TrejGun** [comment]
:+1:

**Comment by p0wl** [comment]
:+1: maybe enable it via a configuration flag, so it is not a problem for people using hmr in production.

**Comment by Sinkler** [comment]
:+1:

**Comment by epsyl** [comment]
:+1:

**Comment by phpdude** [comment]
👍🏻

**Comment by Koshub** [comment]
:+1:

**Comment by ziogaschr** [comment]
:+1:

**Comment by valerymercury** [comment]
:+1:

**Comment by vladmiller** [comment]
:+1: Indeed would be very useful feature.

**Comment by valerybugakov** [comment]
@jantimon can you please suggest how to use your patched version of extract-text-plugin with HMR? I tried your forked repo but it doesn't work for me :( Still getting:
```
[HMR] The following modules couldn't be hot updated: (They would need a full reload!)
```

**Comment by jantimon** [comment]
@valerybugakov The merge request worked - but this was long time ago. As this won't be merged anyway I don't want to spent time on it.

**Comment by valerybugakov** [comment]
@jantimon are you using HMR for CSS right now, somehow? Or just switched to another tool.

**Comment by jantimon** [comment]
I disabled extract text plugin for hmr (in this example if `config.dev` is true):

```
module: {
    loaders: [{
    {
      test: /\.less$/,
      loader: ExtractTextPlugin.extract(
        "style",
        "css-loader",
        "less"
      )
    }],
   plugins: [
      new ExtractTextPlugin("static/styles.css", {
        disable: config.dev
   })
```

**Comment by valerybugakov** [comment]
@jantimon I did the same but then realised that I need sourceMaps (or just sourcePaths) for lots of sass files. With appropriate query parameters I enabled them: ```css?sourceMap!sass?sourceComments!```.
Generated map is placed into style tag and it becomes impossible to edit CSS from developer tools, because of the bad performance. Maybe you know a workaround for this problem?

**Comment by dmydry** [comment]
:+1: Merge it please

**Comment by TrejGun** [comment]
@valerybugakov try this fork
https://github.com/TrejGun/extract-text-webpack-plugin

**Comment by valerybugakov** [comment]
@TrejGun ok, will try, thanks!

**Comment by TrejGun** [comment]
:( doesn't work with `eval` but works with `source-map`

**Comment by jantimon** [comment]
And inline-source-map

**Comment by shepherdwind** [comment]
I just write a loader([css-hot-loader](https://github.com/shepherdwind/css-hot-loader)), which supprot hot module replacement for an extracted css file.

If you don't want use style-loader, maybe you should have a try.

**Comment by bebraw** [comment]
@jantimon Are you still interested? I expect the PR might need some tweaks to make this work in 2 series.

**Comment by jantimon** [comment]
@bebraw thanks for picking this up but I abandoned the related project two years ago because of missing webpack features - the solution is quite simple so it might still work :)

**Comment by bebraw** [comment]
@jantimon Alright. Let's leave this open for now in case someone wants to pick it up for a future release.

**Comment by msuperina** [comment]
Hi I would like to pick up this one, and have 2 options to propose:
- either modify the bundle each time an asset changes: at the moment "// removed by extract-text-webpack-plugin" is written, we could add the hash to this comment
this way it is possible to call module.hot.accept("path/to/asset") in the client application, but then the client would have to manually handle the path of the external resource to reload
- or add a step to the compilation process that takes the output filename and add to the bundle some code that would reload the external resource automatically, like the solution proposed
Note that in both cases I would only modify the loader.js file, not the index.js
Also, the code could be handled by a plugin if you prefer
Finally, an option "hmr: true" could be added to the plugin configuration to enable this feature 
Can you tell me what you prefer before I create a PR please ?

**Comment by bebraw** [comment]
@msuperina Latter sounds good to me especially since then the client doesn't need to worry about dealing with external resources.

@d3viant0ne Any thoughts on this?

**Comment by d3viant0ne** [comment]
Definitely the latter imo.

**Comment by danielverejan** [comment]
@msuperina Any progress with the PR?

**Comment by bebraw** [comment]
@danielverejan Nah. We investigated it, but it's a tough problem (hard code). An interesting way to work around the problem is to go with [extract-loader](https://www.npmjs.com/package/extract-loader). It's not the same, but still worth a look.

**Comment by FrankFan** [comment]
This is a very  useful feature.
It's better to be merged into next version.

**Comment by bebraw** [comment]
If someone wants to work on this, please open a separate PR. It's a surprisingly tough problem to solve neatly.

**Comment by daryn-k** [comment]
Why does not it work for me?

ERROR in ./src/components/App/bootstrap.css
eacthabr-appound Error: Cannot find module "C:site.dev
eactapp
ode_modulesextract-text-webpack-pluginhotModuleReplacement.js"

No idea why a path is such

**Comment by Plortinus** [comment]
Does HMR work in version3.0.0?
