### ISSUE TITLE
Chunk.entry was removed. Use hasRuntime() With Webpack 2.1.0-beta.17

### ISSUE THREAD

**Issue by ashraffayad** [webpack-contrib/extract-text-webpack-plugin#210]
Just updated to Webpack 2.1.0-beta.17
I get this error:
/react-slingshot/node_modules/webpack/lib/Chunk.js:34
        throw new Error("Chunk.entry was removed. Use hasRuntime()");

Error: Chunk.entry was removed. Use hasRuntime()
    at Chunk.Object.defineProperty.get (/node_modules/webpack/lib/Chunk.js:34:9)

Any solution?

**Comment by drborges** [comment]
Seems like this would solve the problem:

```
install extract-text-webpack-plugin@^2.0.0-beta
```

see https://github.com/webpack/webpack/issues/2764

**Comment by ashraffayad** [comment]
Yes, this fixed it. Thanks a lot.

**Comment by jonashaefele** [comment]
I just ran into the same problem.... Cant really go back and can't figure out how to move forward....

When I upgrade extract-text-plugin to 2.0.0-beta I get the following errors (lots of them):

```

ERROR in   Error: Child compilation failed:
  Module build failed: (SystemJS) Error: ENOENT: no such file or directory, open 'PROCECT_ROOT/lodash'

  - Error

  - Error loading PROJECT_ROOT/lodash as "lodash" from /PROJECT_ROOT/node_modules/html-webpack-plugin/lib/loader.js:

  - Error: (SystemJS) Error: ENOENT: no such file or directory, open 'PROJECT_ROOT/lodash'

```

(with `PROJECT_ROOT` being the actual path to the root of my project)

Somehow this makes html-webpack-plugin to try to include lodash and object-assign from project root rather than mode_modules... Might be a problem with html-webpack plugin instead, but the two seem very intertwined in this issue. Any of you ran across this?

Happy to post longer stack trace and configs if if helps...

Using versions:

"webpack": "^2.1.0-beta.19",
"html-webpack-plugin": "git+https://github.com/ampedandwired/html-webpack-plugin.git#93b69a36464c70a3e202b351cc525639224daabb" and also tried with "v2.22.0" (latest on npm)
"extract-text-webpack-plugin": "^2.0.0-beta.2",

**Comment by Kovensky** [comment]
Just to be sure, do you happen to use `postcss-import`? https://github.com/postcss/postcss-import/issues/220

If you do, downgrading to `postcss-import@8.1.0` would fix it.

**Comment by jonashaefele** [comment]
That was exactly it.... thanks a lot!

**Comment by splurtcake** [comment]
@drborges I was having the same issue and upgraded to to the v2 beta, but now getting the following error

```
ERROR in ./src/app/assets/sass/styles.scss
    Module build failed: Unknown word (1:1)
    
    > 1 | // Settings ----------------------------------------------------------------
```

My Webpack config looks like this

```
const styleLoaders = [
	'css?sourceMap',
	'postcss?sourceMap',
	'sass?sourceMap'
];

const paths = {
	src: {
		root: path.join(__dirname, 'src/'),
		styles: 'app/assets/sass/',
	},
	dist: {
		styles: 'css/',
	}
};


export var clientConfig = {
	target: 'web',
	entry: {
		'polyfills': './src/polyfills.browser',
		'vendor': './src/vendor',
		'main': './src/client',
		'styles': './src/app/assets/sass/styles.scss'
	},
	output: {
		path: root('dist/client')
	},
	plugins: [
		new ExtractTextPlugin({
			filename: path.join(paths.dist.styles, 'styles.css'),
			disable: false,
			allChunks: true
		})

	],
	module: {
		loaders: [
			{
				test: /\.scss$/,
				include: path.join(paths.src.root, paths.src.styles),
				loader: ExtractTextPlugin.extract(styleLoaders.join('!'))
			},
		]
	}
};
```

**Comment by drborges** [comment]
@splurtcake have you tried removing `'styles': './src/app/assets/sass/styles.scss'` from the entry section?

The times I worked with `sass` I simply had to configure the [scss loader](https://github.com/jtangelder/sass-loader) and things just worked. If that doesn't work, try sharing the whole stack trace so we may dig a little further.

**Comment by bebraw** [comment]
@splurtcake Can you open a separate issue if that's still present in the current RC?
